name: CRAN Check

on:
  push:
    branches: [ r_package ]
  pull_request:
    branches: [ r_package]
  workflow_dispatch:

jobs:
  R-CMD-check-ubuntu:
    runs: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y zlib1g-dev libbz2-dev liblzma-dev libcurl4-openssl-dev libssl-dev cmake make
      - name: Check package
        run: cd r/Rduckhts && R CMD build . && R CMD check --as-cran .
      - name: Upload check results
        if: failure()
          uses: actions/upload-artifact@v3
          with:
            name: Rduckhts-check-results-ubuntu
            path: r/Rduckhts.Rduckhts.Rcheck/
            retention-days: 30

  R-CMD-check-macos:
    runs: macos-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
      - name: Install system dependencies
        run: brew install htslib cmake
      - name: Check package
        run: cd r/Rduckhts && R CMD build . && R CMD check --as-cran .
      - name: Upload check results
        if: failure()
          uses: actions/upload-artifact@v3
          with:
            name: Rduckhts-check-results-macos
            path: r/Rduckhts.Rduckhts.Rcheck/
            retention-days: 30

  R-CMD-check-windows:
    runs: windows-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - name: Check package
        run: cd r/Rduckhts && R CMD build . && R CMD check --as-cran .
      - name: Upload check results
        if: failure()
          uses: actions/upload-artifact@v3
          with:
            name: Rduckhts-check-results-windows
            path: r/Rduckhts.Rduckhts.Rcheck/
            retention-days: 30
