name: CRAN Check

on:
 # push:
 #   branches: [ main, develop ]
  #pull_request:
  #  branches: [ main ]
  workflow_dispatch:

jobs:
  ubuntu:
    runs: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - run: sudo apt-get update && sudo apt-get install -y zlib1g-dev libbz2-dev liblzma-dev libcurl4-openssl-dev libssl-dev cmake make
      - run: cd r/Rduckhts && R CMD build . && R CMD check --as-cran .
      - uses: actions/upload-artifact@v3
        if: failure()
          with:
            name: check-results-ubuntu
            path: r/Rduckhts.Rduckhts.Rcheck/
            retention-days: 30

  macos:
    runs: macos-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - run: brew install htslib cmake
      - run: cd r/Rduckhts && R CMD build . && R CMD check --as-cran .
      - uses: actions/upload-artifact@v3
        if: failure()
          with:
            name: check-results-macos
            path: r/Rduckhts.Rduckhts.Rcheck/
            retention-days: 30

  windows:
    runs: windows-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - run: cd r/Rduckhts && R CMD build . && R CMD check --as-cran .
      - uses: actions/upload-artifact@v3
        if: failure()
          with:
            name: check-results-windows
            path: r/Rduckhts.Rduckhts.Rcheck/
            retention-days: 30